import type { AgentTool, AgentMessage } from "@earendil-works/pi-agent-core";
import type { Model, Api } from "@earendil-works/pi-ai";
import type { SessionKind } from "./persistence.js";
import type { SkillCatalog } from "./skills.js";

/**
 * Model with an optional apiKey attached at runtime.
 * The upstream pi-ai `Model` interface doesn't include `apiKey` (it lives in `StreamOptions`),
 * but our agent loader attaches it to model objects for convenience.
 */
export interface ModelWithApiKey<TApi extends Api = Api> extends Model<TApi> {
  apiKey?: string;
}

/** Minimal definition for registering a feature unit. */
export interface SubagentDefinition {
  name: string;
  description: string;
  domain: string;

  /** If set, used as-is for the system prompt (bypasses convention file loading). */
  systemPrompt?: string;

  // Caller-managed paths (persisted for resume)
  /** Agent directory containing AGENTS.md, heartbeat.md, knowledge/, workspace/, etc. */
  agentDir?: string;
  /** Canonical installation-relative folder for completion writes, not the immutable source directory. */
  agentRelativeDir?: string;
  workspace?: string;
  /** Directory containing agent knowledge files (INDEX.md, etc.). */
  knowledgeDir?: string;

  /** App ownership metadata used to enforce external/app-local call boundaries. */
  appLocal?: boolean;
  projectId?: string;

  /** Project root / exec cwd. Injected into system prompt as a concrete runtime fact. */
  projectRoot?: string;

  /** Immutable shared prompt/skill source selected with this definition generation. */
  sharedRoot?: string;

  // Capabilities
  tools: AgentTool[];
  model: Model<any>;
  apiKey?: string;
  timeoutMs?: number;

  /**
   * Custom prefix for session IDs generated by run().
   * Defaults to "s" if not set, producing IDs like "s_1234567890_0".
   * When set to e.g. "agent", produces IDs like "agent_1234567890_0".
   */
  sessionIdPrefix?: string;

  memoryLimit?: number; // default 20

  /** Enable automatic context compaction for long-running sessions. */
  compaction?: boolean;

  /**
   * @deprecated Volatile files should be injected as session context, not system prompt.
   * Kept while older agent.json files migrate away from context_files.
   */
  contextFiles?: string[];

  /** Validated, precedence-resolved skill snapshot used by new turns. */
  skillCatalog?: SkillCatalog;

}

/** Runtime info about a session. */
export interface SessionInfo {
  sessionId: string;
  agent: string;
  task: string;
  status: "running" | "done" | "error" | "interrupted" | "idle";
  startedAt: number;
  endedAt?: number;
  runtime: string;
  outputDir: string;
  error?: string;
  /** Last assistant text — useful for resuming interrupted sessions. */
  outcome?: string;
  /** Session that spawned this one (e.g. May's session when a workflow runs a sub-agent). */
  parentSessionId?: string;
  /** Workflow execution that this session belongs to. */
  workflowRunId?: string;
  /** Role of this session in its workflow (e.g. "coder", "reviewer"). */
  stepLabel?: string;
  /** Session lifecycle policy. "never" = persistent/chat session, "immediate" = task session. */
  autoClose?: "immediate" | "never";
  /** Session kind: chat, job, or call. */
  kind?: SessionKind;
  /** Number of state-changing tool calls executed so far. */
  opCount?: number;
  /** LLM turns completed. */
  turnCount?: number;
  /** Structured finish() parameters (context_updates, completed_items, etc). */
  finishParams?: Record<string, unknown>;
  /** Files modified during the session. */
  filesModified?: string[];
  /** Workspace path for this agent. */
  workspacePath?: string;
}

/** Result of a completed session. */
export interface TaskResult {
  sessionId: string;
  status: "done" | "error" | "interrupted";
  lastAssistantText: string | null;
  messages: AgentMessage[];
  duration: string;
  outputDir: string;
  error?: string;
  /** Provider/runtime error surfaced on the terminal assistant message, when present. */
  errorMessage?: string;
  /** Number of assistant turns completed in this session. */
  turnsUsed?: number;
  /** P20 Tainted Handoffs: instability metrics for downstream verification decisions. */
  instability?: InstabilityMetrics;
  /** Structured data from the agent's finish() tool call, if one was made. */
  finishResult?: FinishResult;
  /** Caller-defined, schema-validated payload from finish().result. */
  structuredResult?: unknown;
}

/** P20 Tainted Handoffs: signals indicating result reliability. */
export interface InstabilityMetrics {
  retries: number;
  toolErrors: number;
  turns: number;
  verdict: "clean" | "tainted";
}

/** Structured finish() data from the agent's explicit completion signal. */
export interface FinishResult {
  status: "success" | "failure" | "blocked" | "partial";
  summary: string;
  deliverables?: { path: string; description: string }[];
  blockers?: { reason: string; context: string }[];
  next_steps?: string;
  /** Caller-defined payload for a schema-backed workflow step. */
  result?: unknown;
}

/** Context passed to local tool factories in agents/<name>/tools/. */
export interface ToolContext {
  projectRoot: string;
  agentRoot: string;
  persistDir: string;
}

/** Local tool files must default-export a factory matching this signature. */
export type ToolFactory = (context: ToolContext) => AgentTool | Promise<AgentTool>;
