import type { AgentTool, AgentMessage } from "@mariozechner/pi-agent-core";
import type { Model, Api } from "@mariozechner/pi-ai";
import type { CompactionOptions } from "./compaction.js";
import type { SessionKind } from "./persistence.js";

/**
 * Model with an optional apiKey attached at runtime.
 * The upstream pi-ai `Model` interface doesn't include `apiKey` (it lives in `StreamOptions`),
 * but our agent loader attaches it to model objects for convenience.
 */
export interface ModelWithApiKey<TApi extends Api = Api> extends Model<TApi> {
  apiKey?: string;
}

/** Minimal definition for registering a feature unit. */
export interface SubagentDefinition {
  name: string;
  description: string;
  domain: string;

  /** If set, used as-is for the system prompt (bypasses convention file loading). */
  systemPrompt?: string;

  // Caller-managed paths (persisted for resume)
  workspace?: string;
  /** Directory containing agent knowledge files (INDEX.md, etc.). */
  knowledgeDir?: string;

  /** Project root / exec cwd. Injected into system prompt as a concrete runtime fact. */
  projectRoot?: string;

  // Capabilities
  tools: AgentTool[];
  model: Model<any>;
  apiKey?: string;
  timeoutMs?: number;

  /**
   * Custom prefix for session IDs generated by run().
   * Defaults to "s" if not set, producing IDs like "s_1234567890_0".
   * When set to e.g. "agent", produces IDs like "agent_1234567890_0".
   */
  sessionIdPrefix?: string;

  memoryLimit?: number; // default 20

  /**
   * Enable automatic context compaction for long-running sessions.
   * When message tokens exceed threshold % of context window, older messages
   * are summarized to keep the context under control.
   * Set to `true` for defaults, or pass CompactionOptions for fine-tuning.
   * Only recommended for supervisor/long-running agents, not scoped sub-agents.
   */
  compaction?: boolean | CompactionOptions;

  /**
   * Additional context files to include in the system prompt.
   * Paths are relative to the agent directory (e.g., "conversation-state.md").
   * Loaded after convention files (SOUL.md, DOMAIN.md, etc.) but before
   * the Runtime Environment section.
   */
  contextFiles?: string[];

  /**
   * Operation budget: max number of state-changing tool calls (bash, write, edit, commit)
   * allowed per session. 0 or undefined = unlimited.
   */
  opBudget?: number;

  /** @deprecated Turn budget enforcement removed. Field kept for type compat. */
  turnBudget?: number | Record<string, number>;
}

/** Runtime info about a session. */
export interface SessionInfo {
  sessionId: string;
  agent: string;
  task: string;
  status: "running" | "done" | "error" | "interrupted" | "idle";
  startedAt: number;
  endedAt?: number;
  runtime: string;
  outputDir: string;
  error?: string;
  /** Last assistant text — useful for resuming interrupted sessions. */
  outcome?: string;
  /** Session that spawned this one (e.g. May's session when a workflow runs a sub-agent). */
  parentSessionId?: string;
  /** Workflow execution that this session belongs to. */
  workflowRunId?: string;
  /** Role of this session in its workflow (e.g. "coder", "reviewer"). */
  stepLabel?: string;
  /** Session lifecycle policy. "never" = persistent/chat session, "immediate" = task session. */
  autoClose?: "immediate" | "never";
  /** Session kind: chat, job, or call. */
  kind?: SessionKind;
  /** Number of state-changing tool calls executed so far. */
  opCount?: number;
  /** Operation budget (0 = unlimited). */
  opBudget?: number;
  /** LLM turns completed. */
  turnCount?: number;
  /** Structured finish() parameters (context_updates, completed_items, etc). */
  finishParams?: Record<string, unknown>;
  /** Files modified during the session. */
  filesModified?: string[];
  /** Workspace path for this agent. */
  workspacePath?: string;
}

/** Result of a completed session. */
export interface TaskResult {
  sessionId: string;
  status: "done" | "error" | "interrupted";
  lastAssistantText: string | null;
  messages: AgentMessage[];
  duration: string;
  outputDir: string;
  error?: string;
  /** Number of assistant turns completed in this session. */
  turnsUsed?: number;
  /** P20 Tainted Handoffs: instability metrics for downstream verification decisions. */
  instability?: InstabilityMetrics;
  /** Structured data from the agent's finish() tool call, if one was made. */
  finishResult?: FinishResult;
}

/** P20 Tainted Handoffs: signals indicating result reliability. */
export interface InstabilityMetrics {
  retries: number;
  toolErrors: number;
  turns: number;
  verdict: "clean" | "tainted";
}

/** Structured finish() data from the agent's explicit completion signal. */
export interface FinishResult {
  status: "success" | "failure" | "blocked" | "partial";
  summary: string;
  deliverables?: { path: string; description: string }[];
  blockers?: { reason: string; context: string }[];
  next_steps?: string;
}

/** Context passed to local tool factories in agents/<name>/tools/. */
export interface ToolContext {
  projectRoot: string;
  agentRoot: string;
  persistDir: string;
}

/** Local tool files must default-export a factory matching this signature. */
export type ToolFactory = (context: ToolContext) => AgentTool | Promise<AgentTool>;

/** Recursive tree node representing a session and its children in the session hierarchy. */
export interface SessionTreeNode {
  sessionId: string;
  agent: string;
  task: string;
  status: "running" | "completed" | "cancelled";
  children: SessionTreeNode[];
  result?: string;
}

// ── Health API types ───────────────────────────────────────────────────

/** Active session info returned by health(). */
export interface HealthActiveSession {
  sessionId: string;
  agent: string;
  status: "running" | "interrupted" | "idle";
  startedAt: number;
  runtime: string;
  turnCount: number;
}

/** In-memory health snapshot returned by manager.health(). */
export interface ManagerHealthReport {
  registeredAgents: { count: number; names: string[] };
  activeSessions: HealthActiveSession[];
  sessionCounts: { running: number; idle: number; total: number };
  uptime: string;
  timestamp: string;
}

/** Options for auditHealth(). */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface AuditHealthOptions {
  // Reserved for future options (e.g., agentsRoot, skipBuildChecks).
  // Currently unused — kept as extension point.
}

/** Filesystem-based ground-truth scan returned by manager.auditHealth(). */
export interface AuditHealthReport {
  sessionsLast24h: number;
  unevaluated: { total: number; actionable: number; autoSkippable: number };
  staleSessions: Array<{ sessionId: string; agent: string; task: string }>;
  totalPersistedSessions: number;
  workflowRuns: { total: number; running: number; completed: number; interrupted: number };
  /** All persisted session IDs (for reconciliation without re-scanning). */
  persistedSessionIds: Set<string>;
  timestamp: string;
}

/** Reconciliation report comparing in-memory vs filesystem state. */
export interface ReconcileReport {
  health: ManagerHealthReport;
  audit: AuditHealthReport;
  discrepancies: string[];
  healthy: boolean;
}
