import type { AgentTool, AgentMessage } from "@mariozechner/pi-agent-core";
import type { Model } from "@mariozechner/pi-ai";
import type { CompactionOptions } from "./compaction.js";
import type { SessionKind } from "./persistence.js";

/** Minimal definition for registering a feature unit. */
export interface SubagentDefinition {
  name: string;
  description: string;
  domain: string;

  /** If set, used as-is for the system prompt (bypasses convention file loading). */
  systemPrompt?: string;

  // Caller-managed paths (persisted for resume)
  workspace?: string;
  /** Directory containing agent knowledge files (INDEX.md, etc.). */
  knowledgeDir?: string;

  /** Project root / exec cwd. Injected into system prompt as a concrete runtime fact. */
  projectRoot?: string;

  // Capabilities
  tools: AgentTool[];
  model: Model<any>;
  apiKey?: string;
  timeoutMs?: number;

  /**
   * Custom prefix for session IDs generated by run().
   * Defaults to "s" if not set, producing IDs like "s_1234567890_0".
   * When set to e.g. "agent", produces IDs like "agent_1234567890_0".
   */
  sessionIdPrefix?: string;

  memoryLimit?: number; // default 20

  /**
   * Enable automatic context compaction for long-running sessions.
   * When message tokens exceed threshold % of context window, older messages
   * are summarized to keep the context under control.
   * Set to `true` for defaults, or pass CompactionOptions for fine-tuning.
   * Only recommended for supervisor/long-running agents, not scoped sub-agents.
   */
  compaction?: boolean | CompactionOptions;
}

/** Runtime info about a session. */
export interface SessionInfo {
  sessionId: string;
  agent: string;
  task: string;
  status: "running" | "done" | "error" | "interrupted" | "idle";
  startedAt: number;
  endedAt?: number;
  runtime: string;
  outputDir: string;
  error?: string;
  /** Session that spawned this one (e.g. May's session when a workflow runs a sub-agent). */
  parentSessionId?: string;
  /** Workflow execution that this session belongs to. */
  workflowRunId?: string;
  /** Role of this session in its workflow (e.g. "coder", "reviewer"). */
  stepLabel?: string;
  /** Session lifecycle policy. "never" = persistent/chat session, "immediate" = task session. */
  autoClose?: "immediate" | "never";
  /** Session kind: chat, job, or call. */
  kind?: SessionKind;
}

/** Result of a completed session. */
export interface TaskResult {
  sessionId: string;
  status: "done" | "error";
  lastAssistantText: string | null;
  messages: AgentMessage[];
  duration: string;
  outputDir: string;
  error?: string;
  /** Number of assistant turns completed in this session. */
  turnsUsed?: number;
}

/** Recursive tree node representing a session and its children in the session hierarchy. */
export interface SessionTreeNode {
  sessionId: string;
  agent: string;
  task: string;
  status: "running" | "completed" | "cancelled";
  children: SessionTreeNode[];
  result?: string;
}

// ── Health API types ───────────────────────────────────────────────────

/** Active session info returned by health(). */
export interface HealthActiveSession {
  sessionId: string;
  agent: string;
  status: "running" | "interrupted" | "idle";
  startedAt: number;
  runtime: string;
  turnCount: number;
}

/** In-memory health snapshot returned by manager.health(). */
export interface ManagerHealthReport {
  registeredAgents: { count: number; names: string[] };
  activeSessions: HealthActiveSession[];
  sessionCounts: { running: number; idle: number; total: number };
  uptime: string;
  timestamp: string;
}

/** Options for auditHealth(). */
// eslint-disable-next-line @typescript-eslint/no-empty-object-type
export interface AuditHealthOptions {
  // Reserved for future options (e.g., agentsRoot, skipBuildChecks).
  // Currently unused — kept as extension point.
}

/** Filesystem-based ground-truth scan returned by manager.auditHealth(). */
export interface AuditHealthReport {
  sessionsLast24h: number;
  unevaluated: { total: number; actionable: number; autoSkippable: number };
  staleSessions: Array<{ sessionId: string; agent: string; task: string }>;
  totalPersistedSessions: number;
  workflowRuns: { total: number; running: number; completed: number; interrupted: number };
  /** All persisted session IDs (for reconciliation without re-scanning). */
  persistedSessionIds: Set<string>;
  timestamp: string;
}

/** Reconciliation report comparing in-memory vs filesystem state. */
export interface ReconcileReport {
  health: ManagerHealthReport;
  audit: AuditHealthReport;
  discrepancies: string[];
  healthy: boolean;
}
