/** Stable authoring contract for App declarations and bounded App-owned work. */

export { Type, defineApp, matchesEventSelector } from "./app.js";
export {
  MIN_CONDITION_REVIEW_AFTER_MS,
  admitTaskReconcileResult,
  admitTaskVerificationResult,
  conditionSchema,
  isTypedConditionSubject,
  taskActionSchema,
  taskOwnerResultSchema,
  taskReconcileResultSchema,
  taskVerificationResultSchema,
} from "./task.js";
export type {
  AppAction,
  AppAnalysisRequest,
  AppDefinition,
  AppDependencyObservation,
  AppWorkView,
  AppConversationResource,
  AppConversationMessage,
  AppDisposition,
  AppEvent,
  AppEventSubscription,
  AppEventTarget,
  AppInboxBatchMode,
  AppInput,
  AppInputSource,
  AppObserver,
  AppRead,
  AppRequest,
  AppResult,
  AppSchedule,
  AppTaskAttachment,
  AppTaskPolicy,
  AppWorkspace,
  EventSelector,
  ExecutionResult,
  ExecutionView,
  Logger,
  MetricDefinition,
  MetricRecordOptions,
  MetricView,
  ObserverContext,
  Static,
  TaskView,
  TaskReconciliationChild,
  TaskReconciliationContext,
  TSchema,
  WorkflowContext,
  WorkflowInput,
  WorkflowMetricCapability,
  AgentCallOptions,
} from "./app.js";
export type {
  Condition,
  TaskAcceptanceBasis,
  TaskAction,
  TaskIntent,
  TaskMode,
  TaskPriority,
  TaskReconcileResult,
  TaskReconcileState,
  TaskVerificationContext,
  TaskVerificationResult,
  TaskVerifier,
  TaskReconcileAdmission,
  TaskReconcileAdmissionOptions,
} from "./task.js";
export { workflowResult, workflowResultVersion } from "./workflow-result.js";
export type {
  StructuredWorkflowResult,
  WorkflowCheckResult,
  WorkflowIoContract,
  WorkflowProblem,
  WorkflowResultStatus,
  WorkflowSubject,
} from "./workflow-result.js";
export type {
  Demand,
  GuardModule,
  WorkflowGuard,
  WorkflowGuardCompletedStep,
  WorkflowGuardEvent,
  WorkflowGuardStepResult,
} from "./workflow-guard.js";
