/**
 * Live-stack e2e sandbox.
 *
 * Builds a self-contained directory tree, spawns a real daemon subprocess
 * pointed at it via env vars, and tears everything down on close.
 *
 * Tests must not touch /app/agents, /app/projects, /app/shared, or the host's
 * real .state/. All inputs come from test/e2e/fixtures/ (committed) or are
 * generated by the test itself.
 *
 * Usage:
 *
 *   const sb = await buildSandbox({
 *     fixtureAgents: ["may"],
 *     fixtureHandlers: { may: ["e2e-noop"] },
 *     fixtureProjects: [],
 *     cronJson: { may: { jobs: [...] } },
 *   });
 *   try {
 *     // sb.socketPath, sb.stateDir, sb.projectsRoot, sb.agentsRoot, sb.dbPath
 *     // sb.daemonReady is a Promise that resolves when the socket is up
 *     await sb.daemonReady;
 *     ...
 *   } finally {
 *     await sb.close();
 *   }
 */

import { spawn, type ChildProcess } from "node:child_process";
import {
  cpSync,
  existsSync,
  mkdirSync,
  mkdtempSync,
  rmSync,
  symlinkSync,
  writeFileSync,
} from "node:fs";
import { tmpdir } from "node:os";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath } from "node:url";

// Repo root: this file is test/e2e/lib/sandbox.ts → ../../.. is repo root.
const REPO_ROOT = resolve(dirname(fileURLToPath(import.meta.url)), "..", "..", "..");
const FIXTURES_ROOT = resolve(REPO_ROOT, "test", "e2e", "fixtures");
const MAY_TS = resolve(REPO_ROOT, "src", "app", "may.ts");

export interface SandboxSpec {
  /** Fixture agents to copy from test/e2e/fixtures/agents/ into sandbox agents/. */
  fixtureAgents?: string[];
  /** Per-agent handler fixtures to copy from test/e2e/fixtures/handlers/ into agents/<a>/handlers/. */
  fixtureHandlers?: Record<string, string[]>;
  /** Per-agent workflow fixtures to copy from test/e2e/fixtures/workflows/ into agents/<a>/workflows/. */
  fixtureWorkflows?: Record<string, string[]>;
  /** Per-agent cron.json content to write. */
  cronJson?: Record<string, unknown>;
  /** Fixture project dirs to copy from test/e2e/fixtures/projects/ into sandbox projects/. */
  fixtureProjects?: string[];
  /** Daemon args. Default: ["--cron", "--socket"]. */
  daemonArgs?: string[];
  /** Extra env to pass to daemon. */
  env?: Record<string, string>;
  /** Instance label. Default: "e2e". */
  instance?: string;
  /** Interface agent. Default: "may". */
  interfaceAgent?: string;
  /** How long to wait for daemon socket. Default: 30000ms. */
  startupTimeoutMs?: number;
  /** Capture daemon stdout/stderr to a file in sandbox dir. Default: true. */
  captureLogs?: boolean;
  /**
   * Include the platform UI under projects/platform/ui by copying the repo's
   * ui/ tree into the sandbox. Required for UI-driven tests (E8). Default: false.
   * When true and `fixtureProjects` does not include "platform", a minimal
   * platform project.md is also synthesized so the index route resolves.
   */
  includePlatformUi?: boolean;
}

export interface Sandbox {
  root: string;
  stateDir: string;
  projectsRoot: string;
  agentsRoot: string;
  socketPath: string;
  dbPath: string;
  instance: string;
  daemonPid: number | null;
  daemonReady: Promise<void>;
  /** HTTP port assigned to --web (when daemonArgs include --web). undefined otherwise. */
  webPort?: number;
  /** Wait for the web server to accept HTTP requests. Resolves only if --web is enabled. */
  waitForWeb?: (timeoutMs?: number) => Promise<void>;
  /** Returns daemon stdout+stderr captured so far. Empty if captureLogs is false. */
  getLogs: () => string;
  close: () => Promise<void>;
}

function copyFixtureFile(srcRel: string, destAbs: string): void {
  const src = resolve(FIXTURES_ROOT, srcRel);
  if (!existsSync(src)) {
    throw new Error(`fixture not found: ${srcRel} (looked at ${src})`);
  }
  mkdirSync(dirname(destAbs), { recursive: true });
  cpSync(src, destAbs, { recursive: true });
}

function waitForSocket(socketPath: string, timeoutMs: number, killOnTimeout: () => void): Promise<void> {
  return new Promise((resolveP, reject) => {
    const start = Date.now();
    const tick = () => {
      if (existsSync(socketPath)) {
        resolveP();
        return;
      }
      if (Date.now() - start > timeoutMs) {
        killOnTimeout();
        reject(new Error(`daemon socket not ready within ${timeoutMs}ms: ${socketPath}`));
        return;
      }
      setTimeout(tick, 100);
    };
    tick();
  });
}

export async function buildSandbox(spec: SandboxSpec = {}): Promise<Sandbox> {
  const root = mkdtempSync(join(tmpdir(), "may-e2e-"));
  const stateDir = join(root, ".state");
  const projectsRoot = join(root, "projects");
  const agentsRoot = join(root, "agents");
  const sharedRoot = join(root, "shared");
  const instance = spec.instance ?? "e2e";
  const interfaceAgent = spec.interfaceAgent ?? "may";

  // ── 1. Build sandbox tree ──────────────────────────────────────────
  mkdirSync(stateDir, { recursive: true });
  mkdirSync(projectsRoot, { recursive: true });
  mkdirSync(agentsRoot, { recursive: true });
  mkdirSync(sharedRoot, { recursive: true });

  // Minimal shared/common-sense.md so prompt assembly doesn't fail.
  // Daemon reads this lazily during agent session start; not at boot.
  writeFileSync(join(sharedRoot, "common-sense.md"), "# Test environment\n");

  // Fixture handlers/workflows live under the tmp sandbox and import the public
  // SDK package name, just like real agent-owned code. Expose the workspace SDK
  // inside the sandbox's module tree so runtime dynamic imports resolve from
  // the fixture file location.
  const sdkNodeModulesDir = join(root, "node_modules", "@may-agent");
  mkdirSync(sdkNodeModulesDir, { recursive: true });
  symlinkSync(resolve(REPO_ROOT, "packages", "sdk"), join(sdkNodeModulesDir, "sdk"), "dir");

  // Copy fixture agents (each becomes agents/<name>/).
  for (const name of spec.fixtureAgents ?? []) {
    copyFixtureFile(join("agents", name), join(agentsRoot, name));
  }

  // Copy fixture handlers into per-agent handlers/.
  for (const [agent, handlers] of Object.entries(spec.fixtureHandlers ?? {})) {
    for (const handler of handlers) {
      copyFixtureFile(
        join("handlers", `${handler}.ts`),
        join(agentsRoot, agent, "handlers", `${handler}.ts`),
      );
    }
  }

  // Copy fixture workflows into per-agent workflows/.
  for (const [agent, workflows] of Object.entries(spec.fixtureWorkflows ?? {})) {
    for (const wf of workflows) {
      copyFixtureFile(
        join("workflows", `${wf}.ts`),
        join(agentsRoot, agent, "workflows", `${wf}.ts`),
      );
    }
  }

  // Write per-agent cron.json.
  for (const [agent, cron] of Object.entries(spec.cronJson ?? {})) {
    const cronPath = join(agentsRoot, agent, "cron.json");
    mkdirSync(dirname(cronPath), { recursive: true });
    writeFileSync(cronPath, JSON.stringify(cron, null, 2));
  }

  // Copy fixture projects (each becomes projects/<name>/).
  for (const name of spec.fixtureProjects ?? []) {
    copyFixtureFile(join("projects", name), join(projectsRoot, name));
  }

  // Optional: copy the repo's platform UI into projects/platform/ui so that
  // --web serves the real production UI for UI-driven tests (E8).
  if (spec.includePlatformUi) {
    const platformDir = join(projectsRoot, "platform");
    mkdirSync(platformDir, { recursive: true });
    const uiSrc = resolve(REPO_ROOT, "ui");
    if (!existsSync(uiSrc)) {
      throw new Error(`includePlatformUi requested but repo ui/ not found at ${uiSrc}`);
    }
    cpSync(uiSrc, join(platformDir, "ui"), { recursive: true });
    // Synthesize minimal project.md + discussion.md if not already supplied.
    const projectMd = join(platformDir, "project.md");
    if (!existsSync(projectMd)) {
      writeFileSync(
        projectMd,
        `---\nstatus: waiting\npriority: P2\nowner: agent:may\n---\n\n# Platform (e2e fixture)\n\nMinimal platform project for UI e2e tests.\n`,
      );
    }
    const discussionMd = join(platformDir, "discussion.md");
    if (!existsSync(discussionMd)) {
      writeFileSync(discussionMd, `# discussion\n\n`);
    }
  }

  // ── 2. Spawn daemon ────────────────────────────────────────────────
  const socketPath = resolve(stateDir, "instances", instance, `${interfaceAgent}.sock`);
  const dbPath = resolve(stateDir, "may.db"); // adjust if real path differs
  const logPath = join(root, "daemon.log");
  const captureLogs = spec.captureLogs !== false;
  const logChunks: string[] = [];

  // Allocate a free port for --web if it's in the args.
  const daemonArgs = spec.daemonArgs ?? ["--cron", "--socket"];
  const webEnabled = daemonArgs.includes("--web");
  let webPort: number | undefined;
  if (webEnabled) {
    webPort = await allocateFreePort();
  }

  const env: Record<string, string> = {
    ...process.env as Record<string, string>,
    APP_ROOT: root,
    PROJECT_ROOT: root,
    AGENTS_ROOT: agentsRoot,
    PROJECTS_ROOT: projectsRoot,
    SHARED_ROOT: sharedRoot,
    STATE_DIR: stateDir,
    INSTANCE: instance,
    DAEMON_INSTANCE: instance,
    AGENT: interfaceAgent,
    DAEMON_AGENT: interfaceAgent,
    // Make sure no telegram bot tries to start.
    TELEGRAM_BOT_TOKEN: "",
    TELEGRAM_CHAT_ID: "",
    ...(webPort !== undefined ? { WEB_PORT: String(webPort) } : {}),
    ...spec.env,
  };

  const args = daemonArgs;
  const child: ChildProcess = spawn("bun", [MAY_TS, ...args], {
    cwd: REPO_ROOT,
    env,
    stdio: ["ignore", "pipe", "pipe"],
  });

  if (captureLogs) {
    child.stdout?.on("data", (chunk) => {
      logChunks.push(chunk.toString());
    });
    child.stderr?.on("data", (chunk) => {
      logChunks.push(chunk.toString());
    });
  }

  let exited = false;
  let exitCode: number | null = null;
  child.on("exit", (code) => {
    exited = true;
    exitCode = code;
    if (captureLogs) {
      try {
        writeFileSync(logPath, logChunks.join(""));
      } catch {}
    }
  });

  const startupTimeoutMs = spec.startupTimeoutMs ?? 30000;
  const daemonReady = waitForSocket(socketPath, startupTimeoutMs, () => {
    try {
      child.kill("SIGTERM");
    } catch {}
  }).catch((err) => {
    // Augment error with captured logs for debug.
    const logs = logChunks.join("");
    const exitInfo = exited ? ` (daemon exited with code ${exitCode})` : "";
    throw new Error(`${err.message}${exitInfo}\n--- daemon logs ---\n${logs}\n--- end logs ---`);
  });

  const close = async (): Promise<void> => {
    if (!exited && child.pid) {
      const stopped = new Promise<void>((resolveP) => {
        child.once("exit", () => resolveP());
      });
      try {
        child.kill("SIGTERM");
      } catch {}
      // Force kill after 3s.
      const forceKill = setTimeout(() => {
        try {
          child.kill("SIGKILL");
        } catch {}
      }, 3000);
      await stopped;
      clearTimeout(forceKill);
    }
    if (captureLogs) {
      try {
        writeFileSync(logPath, logChunks.join(""));
      } catch {}
    }
    // Keep sandbox dir if E2E_KEEP=1 for debugging.
    if (!process.env.E2E_KEEP) {
      try {
        rmSync(root, { recursive: true, force: true });
      } catch {}
    }
  };

  return {
    root,
    stateDir,
    projectsRoot,
    agentsRoot,
    socketPath,
    dbPath,
    instance,
    daemonPid: child.pid ?? null,
    daemonReady,
    webPort,
    waitForWeb: webEnabled && webPort !== undefined
      ? (timeoutMs = 15000) => waitForHttp(`http://127.0.0.1:${webPort}/`, timeoutMs)
      : undefined,
    getLogs: () => logChunks.join(""),
    close,
  };
}

async function allocateFreePort(): Promise<number> {
  // Bind a listener on port 0, read the assigned port, immediately close.
  // There is a small race between close and re-bind but it's adequate for tests.
  const net = await import("node:net");
  return new Promise<number>((resolveP, rejectP) => {
    const srv = net.createServer();
    srv.once("error", rejectP);
    srv.listen(0, "127.0.0.1", () => {
      const addr = srv.address();
      if (addr && typeof addr === "object") {
        const port = addr.port;
        srv.close(() => resolveP(port));
      } else {
        srv.close(() => rejectP(new Error("could not allocate port")));
      }
    });
  });
}

async function waitForHttp(url: string, timeoutMs: number): Promise<void> {
  const start = Date.now();
  let lastErr: unknown = null;
  while (Date.now() - start < timeoutMs) {
    try {
      const res = await fetch(url, { method: "GET" });
      // Any HTTP response (including 404) proves the server is listening.
      if (res.status >= 0) return;
    } catch (err) {
      lastErr = err;
    }
    await new Promise((r) => setTimeout(r, 100));
  }
  throw new Error(`waitForHttp timeout after ${timeoutMs}ms: ${url} (last error: ${lastErr instanceof Error ? lastErr.message : String(lastErr)})`);
}
