import type { AgentTool, AgentMessage } from "@mariozechner/pi-agent-core";
import type { Model } from "@mariozechner/pi-ai";
import type { CompactionOptions } from "./compaction.js";

/** Minimal definition for registering a feature unit. */
export interface SubagentDefinition {
  name: string;
  description: string;
  domain: string;

  // System prompt: if systemPrompt is provided, it takes precedence over systemPromptFiles.
  // systemPromptFiles are loaded and concatenated at session start.
  systemPrompt?: string;
  systemPromptFiles?: string[];

  // Caller-managed paths (persisted for resume)
  workspace?: string;
  /** Directory containing agent knowledge files (domain.md, lessons.md, etc.). */
  knowledgeDir?: string;

  /** Directories to scan for skills (SKILL.md files). Per-agent skills dir is auto-added from knowledgeDir. */
  skillsDirs?: string[];

  /** Project root / exec cwd. Injected into system prompt as a concrete runtime fact. */
  projectRoot?: string;

  // Capabilities
  tools: AgentTool[];
  model: Model<any>;
  apiKey?: string;
  timeoutMs?: number;

  /**
   * Maximum number of assistant turns before the session is automatically stopped.
   * A "turn" is one LLM response (tracked via turn_end events from pi-agent-core).
   * When the limit is reached, the session is aborted with a structured error.
   * The error and turn count are included in the TaskResult for diagnosis.
   */
  maxTurns?: number;

  /**
   * Custom prefix for session IDs generated by run().
   * Defaults to "s" if not set, producing IDs like "s_1234567890_0".
   * When set to e.g. "agent", produces IDs like "agent_1234567890_0".
   */
  sessionIdPrefix?: string;

  memoryLimit?: number; // default 20

  /**
   * Enable automatic context compaction for long-running sessions.
   * When message tokens exceed threshold % of context window, older messages
   * are summarized to keep the context under control.
   * Set to `true` for defaults, or pass CompactionOptions for fine-tuning.
   * Only recommended for supervisor/long-running agents, not scoped sub-agents.
   */
  compaction?: boolean | CompactionOptions;
}

/** Runtime info about a session. */
export interface SessionInfo {
  sessionId: string;
  agent: string;
  task: string;
  status: "running" | "done" | "error" | "interrupted";
  startedAt: number;
  endedAt?: number;
  runtime: string;
  outputDir: string;
  lastActivity?: string;
  error?: string;
  /** Session that spawned this one (e.g. May's session when a workflow runs a sub-agent). */
  parentSessionId?: string;
  /** Workflow execution that this session belongs to. */
  workflowRunId?: string;
  /** Role of this session in its workflow (e.g. "coder", "reviewer"). */
  stepLabel?: string;
}

/** Result of a completed session. */
export interface TaskResult {
  sessionId: string;
  status: "done" | "error";
  lastAssistantText: string | null;
  messages: AgentMessage[];
  duration: string;
  outputDir: string;
  error?: string;
  /** Number of assistant turns completed in this session. */
  turnsUsed?: number;
  /** The maxTurns limit that was configured (undefined = no limit). */
  maxTurns?: number;
}
