import type { AgentTool, AgentMessage } from "@mariozechner/pi-agent-core";
import type { Model } from "@mariozechner/pi-ai";
import type { CompactionOptions } from "./compaction.js";

/** Minimal definition for registering a feature unit. */
export interface SubagentDefinition {
  name: string;
  description: string;
  domain: string;

  // System prompt: if systemPrompt is provided, it takes precedence over systemPromptFiles.
  // systemPromptFiles are loaded and concatenated at session start.
  systemPrompt?: string;
  systemPromptFiles?: string[];

  // Caller-managed paths (persisted for resume)
  workspace?: string;
  /** Directory containing agent knowledge files (domain.md, lessons.md, etc.). */
  knowledgeDir?: string;

  /** Directories to scan for skills (SKILL.md files). Per-agent skills dir is auto-added from knowledgeDir. */
  skillsDirs?: string[];

  /** Project root / exec cwd. Injected into system prompt as a concrete runtime fact. */
  projectRoot?: string;

  /**
   * Include a project directory structure tree in the system prompt.
   *
   * When projectRoot is set and this is not `false`, the system prompt
   * will include an indented tree of the project's files and directories.
   * This eliminates the need for agents to run `find`/`ls` commands to
   * orient themselves — a major source of wasted tool calls.
   *
   * - `true` or `undefined` (default): include structure at depth 2
   * - `false`: disable structure injection
   * - `number`: include structure at the specified depth (0 = top-level only)
   *
   * Noise directories (node_modules, .git, dist, etc.) are always excluded.
   * Maximum 200 entries to prevent bloating the prompt for large repos.
   */
  projectStructure?: boolean | number;

  // Capabilities
  tools: AgentTool[];
  model: Model<any>;
  apiKey?: string;
  timeoutMs?: number;

  /**
   * Maximum number of assistant turns before the session is automatically stopped.
   * A "turn" is one LLM response (tracked via turn_end events from pi-agent-core).
   * When the limit is reached, the session is aborted with a structured error.
   * The error and turn count are included in the TaskResult for diagnosis.
   */
  maxTurns?: number;

  /**
   * Fraction of maxTurns at which to inject a warning message via steer().
   * The warning tells the agent how many turns remain and to wrap up.
   * Fires once. Value between 0 and 1.
   * Default: 0.8 (e.g., at turn 32 of 40).
   * Ignored if maxTurns is not set.
   */
  turnWarningThreshold?: number;

  /**
   * Custom prefix for session IDs generated by run().
   * Defaults to "s" if not set, producing IDs like "s_1234567890_0".
   * When set to e.g. "agent", produces IDs like "agent_1234567890_0".
   */
  sessionIdPrefix?: string;

  memoryLimit?: number; // default 20

  /**
   * Enable automatic context compaction for long-running sessions.
   * When message tokens exceed threshold % of context window, older messages
   * are summarized to keep the context under control.
   * Set to `true` for defaults, or pass CompactionOptions for fine-tuning.
   * Only recommended for supervisor/long-running agents, not scoped sub-agents.
   */
  compaction?: boolean | CompactionOptions;

}

/** Runtime info about a session. */
export interface SessionInfo {
  sessionId: string;
  agent: string;
  task: string;
  status: "running" | "done" | "error" | "interrupted" | "idle";
  startedAt: number;
  endedAt?: number;
  runtime: string;
  outputDir: string;
  error?: string;
  /** Session that spawned this one (e.g. May's session when a workflow runs a sub-agent). */
  parentSessionId?: string;
  /** Workflow execution that this session belongs to. */
  workflowRunId?: string;
  /** Role of this session in its workflow (e.g. "coder", "reviewer"). */
  stepLabel?: string;
}

/** Result of a completed session. */
export interface TaskResult {
  sessionId: string;
  status: "done" | "error";
  lastAssistantText: string | null;
  messages: AgentMessage[];
  duration: string;
  outputDir: string;
  error?: string;
  /** Number of assistant turns completed in this session. */
  turnsUsed?: number;
  /** The maxTurns limit that was configured (undefined = no limit). */
  maxTurns?: number;
}

/** Recursive tree node representing a session and its children in the session hierarchy. */
export interface SessionTreeNode {
  sessionId: string;
  agent: string;
  task: string;
  status: "running" | "completed" | "cancelled";
  children: SessionTreeNode[];
  result?: string;
}

// ── Health API types ───────────────────────────────────────────────────

/** Active session info returned by health(). */
export interface HealthActiveSession {
  sessionId: string;
  agent: string;
  status: "running" | "interrupted" | "idle";
  startedAt: number;
  runtime: string;
  turnCount: number;
  maxTurns?: number;
}

/** In-memory health snapshot returned by manager.health(). */
export interface ManagerHealthReport {
  registeredAgents: { count: number; names: string[] };
  activeSessions: HealthActiveSession[];
  sessionCounts: { running: number; idle: number; total: number };
  uptime: string;
  timestamp: string;
}

/** Options for auditHealth(). */
export interface AuditHealthOptions {
  // Reserved for future options (e.g., agentsRoot, skipBuildChecks).
  // Currently unused — kept as extension point.
}

/** Filesystem-based ground-truth scan returned by manager.auditHealth(). */
export interface AuditHealthReport {
  sessionsLast24h: number;
  unevaluated: { total: number; actionable: number; autoSkippable: number };
  staleSessions: Array<{ sessionId: string; agent: string; task: string }>;
  totalPersistedSessions: number;
  workflowRuns: { total: number; running: number; completed: number; interrupted: number };
  /** All persisted session IDs (for reconciliation without re-scanning). */
  persistedSessionIds: Set<string>;
  timestamp: string;
}

/** Reconciliation report comparing in-memory vs filesystem state. */
export interface ReconcileReport {
  health: ManagerHealthReport;
  audit: AuditHealthReport;
  discrepancies: string[];
  healthy: boolean;
}
